language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - r-lib/covr

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'
warnings_are_errors: true

env:
- _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov(function_exclusions = c("convert\\_old*"), line_exclusions = list("R/zzz.R", "R/psislw.R", "R/effective_sample_sizes.R" = c(74:81, 126:136), "R/psis.R"= c(245:253), "R/loo.R" = c(288:301)))'

