language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - r-lib/covr

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'
warnings_are_errors: true

env:
- _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = c("R/zzz.R", "R/psislw.R"), function_exclusions = c("convert\\_old*"))'
