on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage-mac:
    name: "Mac"
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: R-CMD-check.yaml
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
        
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-1-

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

  test-coverage-windows:
    name: "Windows"
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      # - name: Set path for RTools 4.0
      #   if: runner.os == 'Windows'
      #   run: echo "C:/rtools40/usr/bin;C:/rtools40/mingw64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      #
      # - name: Install mingw32-make and check toolchain path
      #   if: runner.os == 'Windows'
      #   run: |
      #     pacman -Syu mingw-w64-x86_64-make --noconfirm
      #     g++ --version
      #     Get-Command g++ | Select-Object -ExpandProperty Definition
      #     mingw32-make --version
      #     Get-Command mingw32-make | Select-Object -ExpandProperty Definition
      #   shell: powershell

      - uses: r-lib/actions/setup-r@master
        with:
              r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      # - name: Test coverage
      #   run: |
      #     options(covr.gcov = 'C:/rtools40/mingw64/bin/gcov.exe');
      #     covr::codecov(type = "all")
      #   shell: Rscript {0}
